language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 2.0.0-preview2-006497
before_script:
  - dotnet restore
script:  
  - dotnet test ./test/QuartzHostedService.Test -c Release -f netcoreapp2.0
  - dotnet build -c Release