language: csharp  
sudo: required  
dist: xenial  
mono: none
dotnet: 2.2.101
before_script:
  - dotnet restore
script:  
  - dotnet test ./test/QuartzHostedService.Test -c Release
  - dotnet build -c Release